print('Please enter the following information:')
print()
first = input('first_name:')
last = input('last_name:')
email = input('Email_address:')
phone_nunmber = input('Phone_number:')
job_title = input('Jobe_title:')
id_number = input('ID_Number:')
print()
print('The ID Card is')
print('-------------------------')
print(f'{last.upper()} {first.capitalize()}')
print('job_title')
print(f"ID: {id_number}")
print()
print('email.lower')
print('phone_number')
print('-------------------------')

